import { act, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { useTimer } from '@/hooks/useTimer';
import { useTasks } from '@/hooks/useTasks';
import { TIMER_KEY } from '@/lib/timerState';
vi.mock('@/lib/timerAlarm', () => ({ syncAlarm: vi.fn(async () => ''), requestAlarmPermissions: vi.fn(async () => {}) }));
vi.mock('@/utils/soundPlayer', () => ({ soundPlayer: { playRingtone: vi.fn(), stopSound: vi.fn() } }));
beforeEach(() => { localStorage.clear(); vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-14T10:00:00')); });
afterEach(() => { vi.useRealTimers(); });
const flush = async (fn: () => void) => { await act(async () => { fn(); }); };
describe('durable timer', () => {
  it('catches up after suspended JavaScript, caps the end, and records once after reload', async () => {
    const callback = vi.fn();
    const first = renderHook(() => useTimer({ initialDuration: 60, onSessionComplete: callback }));
    await act(async () => { await first.result.current.startFocus(); });
    vi.setSystemTime(Date.now() + 90000);
    await flush(() => document.dispatchEvent(new Event('visibilitychange')));
    expect(first.result.current.history).toHaveLength(1);
    expect(first.result.current.history[0].focusTime).toBe(60);
    expect(first.result.current.history[0].endedAt - first.result.current.history[0].startedAt).toBe(60000);
    await flush(() => vi.advanceTimersByTime(2000));
    expect(callback).toHaveBeenCalledTimes(1);
    first.unmount();
    const second = renderHook(() => useTimer());
    expect(second.result.current.history).toHaveLength(1);
    expect(second.result.current.session.status).toBe('completed');
    second.unmount();
  });
  it('separates focus and break, excludes pause, and saves early stop including fractions', async () => {
    const hook = renderHook(() => useTimer());
    await act(async () => { await hook.result.current.startFocus('task'); });
    vi.setSystemTime(Date.now() + 10500);
    await flush(() => hook.result.current.startBreak());
    vi.setSystemTime(Date.now() + 5250);
    await flush(() => hook.result.current.pause());
    vi.setSystemTime(Date.now() + 120000);
    await flush(() => hook.result.current.resume());
    vi.setSystemTime(Date.now() + 2000);
    await flush(() => hook.result.current.stop());
    const record = hook.result.current.history[0];
    expect(record.focusTime).toBe(10.5);
    expect(record.breakTime).toBe(7.25);
    expect(record.outcome).toBe('ended-early');
    await flush(() => hook.result.current.completeEarly());
    expect(hook.result.current.history).toHaveLength(1);
    hook.unmount();
  });
  it('restores a running timer and preserves paused state through remount', async () => {
    const first = renderHook(() => useTimer());
    await act(async () => { await first.result.current.startFocus(); });
    first.unmount();
    vi.setSystemTime(Date.now() + 10000);
    const second = renderHook(() => useTimer());
    expect(second.result.current.session.elapsed).toBe(10);
    await flush(() => second.result.current.pause());
    second.unmount();
    vi.setSystemTime(Date.now() + 60000);
    const third = renderHook(() => useTimer());
    expect(third.result.current.isPaused).toBe(true);
    expect(third.result.current.session.elapsed).toBe(10);
    third.unmount();
  });
  it('reset saves partial time and task totals remain idempotent alongside legacy values', async () => {
    localStorage.setItem('lockin-tasks', JSON.stringify([{ id: 't', title: 'Read', description: '', deadline: null, createdAt: new Date(), completed: false, focusTime: 120, breakTime: 30 }]));
    const hook = renderHook(() => { const timer = useTimer(); return { timer, tasks: useTasks(timer.history) }; });
    await act(async () => { await hook.result.current.timer.startFocus('t'); });
    vi.setSystemTime(Date.now() + 20000);
    await flush(() => hook.result.current.timer.reset());
    expect(hook.result.current.tasks.tasks[0].focusTime).toBe(140);
    expect(hook.result.current.tasks.tasks[0].completed).toBe(false);
    expect(JSON.parse(localStorage.getItem('lockin-tasks')!)[0].focusTime).toBe(120);
    hook.rerender();
    expect(hook.result.current.tasks.tasks[0].focusTime).toBe(140);
    expect(JSON.parse(localStorage.getItem(TIMER_KEY)!).history).toHaveLength(1);
    hook.unmount();
  });
});
